### ISSUE TITLE
Running into limits with describes

### ISSUE THREAD

**Issue by keithmancuso** [developerforce/Force.com-JavaScript-REST-Toolkit#51]
We are running into describe limits for fields with more than 100 picklists, any suggestions on how to deal with that?

**Comment by metadaddy-sfdc** [comment]
As of the Summer '14 release the describe limits were removed so this should no longer be a problem.

From the [release notes](http://docs.releasenotes.salesforce.com/en-us/summer14/release-notes/rn_apex_describe_limit_removal.htm):

> Limits for all Apex describe calls have been removed for all API versions. Describe calls include describes for sObjects, fields, field sets, child relationships, picklists, and record types.
> 
> You’re no longer limited to describing 100 objects or to executing 100 describe statements.

Feel free to reopen the issue if you're still seeing a problem.
