### ISSUE TITLE
SalesForce username+password authorization

### ISSUE THREAD

**Issue by vnickolov** [developerforce/Force.com-JavaScript-REST-Toolkit#58]
Hi, 

Is there a way to use the username+password authorization?

Thank you in advance.

**Comment by hdramos** [comment]
You need to make POST request like this:

              $.ajax({
                type: "POST",
                url: self.requestUrl,
                data: {
                    'client_secret': self.secret,
                    'grant_type': self.grantType,
                    'client_id': self.clientId,
                    'username': username,
                    'password': password
                }
            });

**Comment by vnickolov** [comment]
Thank you!

**Comment by metadaddy-sfdc** [comment]
@vnickolov OK to close this issue?

**Comment by vnickolov** [comment]
Yes, of course, sorry I didn't close it earlier.
