### ISSUE TITLE
How to perform bulk DML operations in salesforce hybrid app ?

### ISSUE THREAD

**Issue by ramsabarish** [developerforce/Force.com-JavaScript-REST-Toolkit#63]
I have created a  salesforce hybrid app  using  Forceios  and  I'm able  to perform the CRUD operations using forcetk client instance .

Now I want to perform  mass  update on  salesforce  objects  but I didn't find any running example code to do so. 

For 2 days I have searched for topics like  BULK API, SmartSync , JSForce  but I don't understand  how to implement them.

Kindly share a code to perform Bulk DML operations  like  mass update , mass delete through  salesforce hybrid app.    

Kindly Help me out ....

**Comment by metadaddy-sfdc** [comment]
I wrote a Bulk API plugin for ForceTK. Check it out: https://developer.salesforce.com/blogs/developer-relations/2015/03/bulktk-calling-force-com-bulk-api-visualforce-pages.html

Let me know how it works for you and I'll close the issue.

**Comment by ramsabarish** [comment]
How to include Bulk API plugin in hybrid app or how to download  bulktk.js.
 I'm not using visualforce pages in my mobile app.
 
 Kindly help me.

**Comment by metadaddy-sfdc** [comment]
It's just like using ForceTK. Are you using the Salesforce Mobile SDK for your hybrid app, or PhoneGap?

**Comment by ramsabarish** [comment]
Well I'm using Salesforce Mobile SDK in hybrid app.

**Comment by metadaddy-sfdc** [comment]
The technique I outlined in that blog post will work with Mobile SDK just as well. You would need to add bulktk.js to the project (drop it in the same directory as forcetk.js), then you should be able to use the BulkTK calls with the same `client` object. Right now I don't have the correct Mac OS on my laptop to run the latest Mobile SDK, but if you give me a little while I should be able to create a demo app.

**Comment by metadaddy-sfdc** [comment]
Assuming you got this working and I can close the issue. Feel free to reopen it if you're still having problems.
