### ISSUE TITLE
SalesforceProxy-Endpoint not defined in header

### ISSUE THREAD

**Issue by scottmcclung** [developerforce/Force.com-JavaScript-REST-Toolkit#64]
I must be missing something simple.
I've implemented the bulk.page example in a sandbox without any modifications but I am getting a 400 response with the error "SalesforceProxy-Endpoint not defined in header" when attempting to create the job.
Any thoughts on what I forgot to do?  Thanks!

**Comment by metadaddy-sfdc** [comment]
My bad - I fixed this, committed it (c3edd29) but forgot to push. Should work now!

**Comment by scottmcclung** [comment]
Woot!  Working great now.
Thank you for working on this!

**Comment by chavanshama88** [comment]
Hi,
I am trying to use your code in my sandbox but i am getting error 
HTTP ERROR 400 Problem accessing /services/proxy. Reason:
Unable to forward request due to: Stream closed
Can you please help me resolve it?
