### ISSUE TITLE
Add file to specific record's feed

### ISSUE THREAD

**Issue by jonathanwiesel** [developerforce/Force.com-JavaScript-REST-Toolkit#71]
Is it possible to add a file related to an sobject record's chatter feed?

**Comment by metadaddy-sfdc** [comment]
Yes - you could use the `createBlob` sample in the [README](https://github.com/developerforce/Force.com-JavaScript-REST-Toolkit/blob/master/README.markdown), then pass the created file's record id to a remote function in your Apex controller that [posts it to the record's feed](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/connectapi_examples_post_feed_element_content.htm).

Let me know if you need more help or clarification, or just close the issue if you're all set.

**Comment by jonathanwiesel** [comment]
Great, thanks
