### ISSUE TITLE
Proxy for apexrest

### ISSUE THREAD

**Issue by rakeshrockb** [developerforce/Force.com-JavaScript-REST-Toolkit#77]
Hi @metadaddy , Do we have an example anywhere on how to make proxy call for apexrest service?. From the documentation  we need proxy for apexrest , but I have my app in mobilesdk where I don't have any source URL nor my page is hosted in visualforce page. Please advise on how to call my apex class from force.com mobilesdk using forcetk plugin. Thanks in advance.

**Comment by metadaddy-sfdc** [comment]
If you're on mobile (including in Mobile SDK) you don't need the proxy, since you're not in the same sandbox as JS in the regular browser. You will need to add endpoints to the whitelist in the app config.

**Comment by rakeshrockb** [comment]
Thanks so much @metadaddy-sfdc  for super fast response. 
Here is the signature for apexrest in forcetk,mobilesdk.js 
forcetk.Client.prototype.apexrest = function(path, method, payload, headerParams, callback, error) {....} 
I want to call a method in apex with POST annotation which has few arguments. I think this arguments passed as JSON string goes to payload argument in above method and I'm passing null as headerparams, but this is not working for me :(. Am I missing anything?.

**Comment by rakeshrockb** [comment]
I tried vice versa by passing payload as null and headerparams as params for my apex method too with no luck.. Thanks in advance.

**Comment by rakeshrockb** [comment]
Actually, my bad. This is straightforward , I was passing incorrect payload structure. Thanks again.
