### ISSUE TITLE
Office docs corrupt on download from SF UI after loading with forcetk.js with VF sample

### ISSUE THREAD

**Issue by dameyer** [developerforce/Force.com-JavaScript-REST-Toolkit#80]
I'm using the sample listed on the repo to load files from a vf page with forcetk.js as a static resource.
Text files, gif, pdf, office docs all load from the vf page successfully.
However after I download office docs from the SFDC UI and try to open them they are corrupted.
The same files uploaded by the SFDC UI then downloaded open correctly
Text, gifs, pdfs open fine.

**Comment by metadaddy-sfdc** [comment]
I merged a pull request recently (Oct 7) that might fix this - see commit 217010d - are you using a forcetk.js older than that?

**Comment by dameyer** [comment]
I was using the latest. I changed the double newline to one. Works. Thanks Pat.
