### ISSUE TITLE
IE11 browser Issue: Facing issue with Forcetk.js(Rest toolkit), Parameter is incorrect

### ISSUE THREAD

**Issue by surendranune** [developerforce/Force.com-JavaScript-REST-Toolkit#84]
Hi,

I am using IE11 browser. I am using Forcetk.js to for file upload into content version. The script is working fine in Mozilla and Chrome.

But in IE11, I get the below error in Forcetk.js file. Please help if any one faced similar issue.

![forcetk js error](https://cloud.githubusercontent.com/assets/8072534/13312663/7da06e7e-dbbe-11e5-9b08-fe28fd3f220c.JPG)

I have posted the same issue here:
[http://salesforce.stackexchange.com/questions/111774/ie11-browser-issue-facing-issue-with-forcetk-jsrest-toolkit-parameter-is-inc?noredirect=1#comment154859_111774](url)

**Comment by metadaddy-sfdc** [comment]
Sending a blob has been supported in IE since version 10, so I'm a bit puzzled as to the problem. Can you put a breakpoint or a `console.log` in at that line and see what the value of blob is?

**Comment by surendranune** [comment]
Please check the below screenshot for console log.

![console log](https://cloud.githubusercontent.com/assets/8072534/13343645/9ee89e1a-dc74-11e5-84e2-36a7136829cc.JPG)

**Comment by metadaddy-sfdc** [comment]
I'm stumped. I don't have a Windows machine with IE11 to try this on. Everything I can find says this should work on IE11. Is it possible to get more details on the exception?

**Comment by surendranune** [comment]
Hi Patterson,

I too got stumped over debugging this issue!

I finally found the root cause of this issue. I was using "rerender" attribute in my visualforce page. It was due to this, I am getting this error. 

I tried creating a new visualforce page without "rerender" attributes. Then the  file upload was working fine.

Thank you very much for the follow up.
